#--------------------------------------------------------------
# This is a basic workflow to help you get started with Actions
#
#--------------------------------------------------------------
name: MyGHaction_baseJob

# Controls when the workflow will run

on:
  push:
    branches: 
      - master
jobs:
  my_testing:
    runs-on: [ubuntu-latest]
    steps:
      - name: Priont message
        run : echo "Hello Success"
    
    

